### PR TITLE
Add importing multiple data files and grid-plotting

### LINKED ISSUE #1: Plots: average by age, gender over multiple output CSVs
The current R plotting script `Visualization.R` at https://github.com/imperialCHEPI/healthgps-plots takes in a fixed number of output CSV files and averages data over age and gender, weighted by group size, separated into baseline and intervention scenarios.

It would be useful to allow an arbitrary number of files to be fed in and averaged in this way. This would allow us to plot results from HPC array jobs, with multiple output files for each job array index.

as before, we should be careful to weight the average by `count` for each group, and ensure that baseline and intervention data points are separated correctly -- the ordering of baseline and intervention results is not guaranteed.

### PR DESCRIPTION
**Pull request by jzhu20**
Add my commands on importing multiple data files in a directory (can be modified)
Update plotting and add grid-plotting commands
Update reshaping and calculating difference
Re-structure the script

### CODE REVIEW

**Review by TinyMarsh — CHANGES_REQUESTED** [review]
Thanks @jzhu20, just needs a few changes before merging.

Are you running the script as per the instructions in the README? I understand there's probably more efficient ways for you to run this script on your machine, but for the purposes of keeping this repository reusable it's probably best we develop according to the instructions in the README as it guarantees that anyone who clones this repository can run the code. It will also help capture problems as they arise.

The first thing I noticed is that there are a couple of additional libraries being used, but the `renv.lock` file has not been updated to reflect that. When I tried to run the script it complained that I didn't have those libraries installed. The README contains instructions on how to update the `renv.lock` file.

The other thing I noticed is that we now have two ways of loading the data files into the script that are potentially incompatible with each other. The first way fetches data files from the command line (where there is still a requirement that 4 must be specified). The second way searches for all files in the current directory ending in `.csv`. I think we should pick one method and stick with it. Personally I prefer the command line way but it's open for discussion.

**Comment by jzhu20** [comment]
Thanks @TinyMarsh. My response and comments are:

1. At first, I received "Rscript command not found" which might be a common issue. Path of R needs to be added using, e.g.
$Env:PATH +=  "C:\Program Files\R\R-4.3.2\bin"

2. I changed the R script again and updated renv.lock file as well. I kept both ways of importing multiple files as Option 1 (command line) and Option 2 (all csv files in the directory) and added one line of combining dataframes in option 1, because we will need to combine all the simulation results (csv files) to take weighted mean and plot. From my perspective, option 2 is more convenient when importing a large number of csv files, like 50 or 100. Option 1 is more flexible if we need to import, e.g. 20 of the 50 simulation results. We can keep both maybe.

3. Actually I've got error message when running R script, as described in #1.

**Comment by jzhu20** [comment]
Sorry I tried to make changes in this PR but ended up creating a new PR #4 . Apologize for this.

**Comment by TinyMarsh** [comment]
@jzhu20 did you have any code changes in this PR that you wanted to keep? If not we can close this PR and continue with #4.

**Pull request closed without merging**
